### PR TITLE
fix: updates resources for OO and p-o

### LINKED ISSUE #166: Review resources set in components
Currently, our deployment of Prometheus Operator (p-o) set's the following resources:
```yaml
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
This is an extremely tight window of resources that p-o might hit easily, some users already reported to have hit OOM.
AFAIK we should never set limits on infrastructure components, so I suggest us removing completely the `limits`.

### PR DESCRIPTION
**Pull request by JoaoBraveCoding**
Problem: we pull the Prometheus Operator (p-o) deployment from
the upstream repo as a dependency. However this manifest sets
a very low limit to the p-o resources, this limit is easily hit
when the operator is managing multiple Prometheus instances.

Solution: remove current limits and load testing on OO and p-o
and observe the resources they consume. Establish a baseline for
both and then multiply that baseline by 3 and give some headroom

Issue https://issues.redhat.com/browse/MON-2648
Closes https://github.com/rhobs/observability-operator/issues/166

### CODE REVIEW

**Review by simonpasquier — APPROVED** [review]
lgtm

should we do the same for the observability operator deployment?

**Comment by apahim** [comment]
please do set proper resources. see comment in https://issues.redhat.com/browse/MON-2648

**Review by simonpasquier — CHANGES_REQUESTED** [review]
Following Amador's comment, we need to increase limits, not removing them.

File: hack/loadtest/test.sh [hunk 1]
```diff
@@ -0,0 +1,44 @@
+set -e
```
Comment (sthaha) [inline hack/loadtest/test.sh:1]:
```suggestion
#! /usr/bin/env bash

set -eux -o pipefail
```

File: hack/loadtest/test.sh [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+
+# Functions that given a number it creates a namespace
+# and in that namespace it creates a monitoring stack
+function create_monitoring_stack() {
```
Comment (sthaha) [inline hack/loadtest/test.sh:5]:
```suggestion
create_monitoring_stack() {
```

File: hack/loadtest/test.sh [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+    stack_number=$1
+    export MS_NAME=stack-$stack_number
+    export NAMESPACE=loadtest-$stack_number
+
+    monitoring_stack="apiVersion: monitoring.rhobs/v1alpha1
```
Comment (sthaha) [inline hack/loadtest/test.sh:10]: it may be better to read from the samples, or a test-data directory.

File: hack/loadtest/test.sh [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+# Give some time for OO to reconcile all the MS
+# and create the necessary resources
+sleep 180
+
+# Cleanup
+for ((i=1; i<=10; i++))
+do
+    kubectl delete ns loadtest-$i 
+done
```
Comment (sthaha) [inline hack/loadtest/test.sh:44]:
```suggestion
cleanup() { 
    kubectl delete ns loadtest-{1..10}
}

main() {

  # Goal: create 10 monitoring stack CRs, wait for OO to
  # reconcile and then clean-up

  for ((i=1; i<=10; i++)); do
    create_monitoring_stack $i
  done

  # Give some time for OO to reconcile all the MS
  # and create the necessary resources
  sleep 180
  
  cleanup
}

 main "$@"
```

File: hack/loadtest/test.sh [hunk 5]
```diff
@@ -0,0 +1,44 @@
+set -e
+
+# Functions that given a number it creates a namespace
+# and in that namespace it creates a monitoring stack
+function create_monitoring_stack() {
+    stack_number=$1
+    export MS_NAME=stack-$stack_number
```
Comment (sthaha) [inline hack/loadtest/test.sh:7]: we don't need to export these

File: deploy/dependencies/kustomization.yaml [hunk 6]
```diff
@@ -39,6 +39,9 @@ patches:
                   requests:
                     cpu: 5m
                     memory: 150Mi
+                  limits:
+                    cpu: 100m
+                    memory: 500Mi
```
Comment (sthaha) [inline deploy/dependencies/kustomization.yaml:44]: I am a bit confused why the PR which says remove limits from PO adds limits 🤔

File: hack/loadtest/test.sh (hunk 3 above)
Comment (sthaha) [reply hack/loadtest/test.sh:10]: I think it is better to use heredocs instead e.g. 

read -r -d '' VAR <<- EO_YAML
     apiVersion: 
     kind:
     metadata: ...
EO_YAML

File: docs/assessResources.md [hunk 7]
```diff
@@ -0,0 +1,42 @@
+
+# Procedure to assess resources used by Observability Operator
```
Comment (sthaha) [inline docs/assessResources.md:2]: nice!

File: docs/assessResources.md [hunk 8]
```diff
@@ -0,0 +1,42 @@
+
```
Comment (sthaha) [inline docs/assessResources.md:1]: Could we please keep all filenames lowercase?

File: docs/assessResources.md [hunk 9]
```diff
@@ -0,0 +1,42 @@
...
+2. Run `oc apply -f hack/olm/catalog-src.yaml` to install the Observability Operator (OO) catalogue.
+
+3. Using the UI install OO
+
+4. Scale down the following deployments, so we can remove the currently set limits on OO:
+
+```bash
+# Scale down the cluster version operator
+oc -n openshift-cluster-version scale deployment.apps/cluster-version-operator --replicas=0
```
Comment (sthaha) [inline docs/assessResources.md:14]: should we scale down the CVO? Can't we edit the cluster-version to put OLM in unmanaged mode? 🤔

File: docs/assessResources.md [hunk 10]
```diff
@@ -0,0 +1,42 @@
...
+# Scale down the OLM operator
+oc -n openshift-operator-lifecycle-manager scale deployment.apps/olm-operator --replicas=0
+```
+
+5. Edit the OO and Prometheus Operator deployment to remove it's limits with:
+
+```bash
+oc -n openshift-operators edit deployment.apps/observability-operator
```
Comment (sthaha) [inline docs/assessResources.md:22]: just a thought - can we use `patch`  instead?

**Comment by sthaha** [comment]
FYI: I am looking e2e-test-olm failure #170

File: hack/loadtest/test.sh (hunk 3 above)
Comment (JoaoBraveCoding) [reply hack/loadtest/test.sh:10]: From StackOverflow:
> I think it's worth mentioning that if you have set -o errexit (a.k.a set -e) in your script and you use this then it will terminate your script because read returns a non-zero return code when it reaches EOF.

Still, I've updated it to use heredoc

File: hack/loadtest/test.sh [hunk 11]
```diff
@@ -0,0 +1,50 @@
...
+spec:
+  logLevel: debug
+  retention: 15d
+  resourceSelector:
+    matchLabels:
+      load-test-instance: ${MS_NAME}
+EOF
+)
+
+    kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
```
Comment (sthaha) [inline hack/loadtest/test.sh:29]: can't we `kubectl create ns $namespace` ?

**Comment by sthaha** [comment]
@JoaoBraveCoding I felt running cleanup on SIGINT will be a good addition. PTAL - https://github.com/JoaoBraveCoding/observability-operator/pull/1 👼

**Review by simonpasquier — APPROVED** [review]
lgtm

**Comment by simonpasquier** [comment]
> @JoaoBraveCoding Does this patch completely addresses https://issues.redhat.com/browse/MON-2648
> 
> Should there be a change for PO as well?

IIUC this PR updates the limits for both OBO and PO. If you mean updating the limits in https://github.com/prometheus-operator/prometheus-operator, the values are based on what is required to run the end-to-end tests.

**Comment by JoaoBraveCoding** [comment]
> @JoaoBraveCoding Does this patch completely addresses https://issues.redhat.com/browse/MON-2648
> 
> Should there be a change for PO as well?

Yes, but that is also done in this PR in the file (`deploy/dependencies/kustomization.yaml`). I'll let you press merge @sthaha if everything looks good to you 😄
